services:
  backend:
    container_name: fastapi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - .env
  #frontend:
    #container_name: react_frontend
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile
    #volumes:
      #- TODO
    #ports:
      #- "3000:3000"
    #command: TODO
    #restart: always
    #healthcheck: TODO