name: Deploy Gmail WatcherCloud Function

on:
  push:
    branches:
      - main
    paths:
      - 'cloud_functions/gmail_watcher'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy Cloud Function
      working-directory: ./cloud_functions/gmail_watcher
      run: |
        gcloud functions deploy gmail_watcher \
          --runtime python312 \
          --trigger-http \
          --entry-point gmail_watcher_main \
          --region us-central1 \
          --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}, OAUTH_TOKEN_SECRET_ID=${{ vars.OAUTH_TOKEN_SECRET_ID }}, EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}, MESSAGE_PROCESSING_COLLECTION=${{ vars.MESSAGE_PROCESSING_COLLECTION }}, PUBSUB_TOPIC_ID=${{ vars.PUBSUB_TOPIC_ID }}, VENMO_EMAIL=${{ vars.VENMO_EMAIL }}, AMEX_EMAIL=${{ vars.AMEX_EMAIL }}, CHASE_EMAIL=${{ vars.CHASE_EMAIL }}, CAPITALONE_EMAIL=${{ vars.CAPITALONE_EMAIL }}, WELLSFARGO_EMAIL=${{ vars.WELLSFARGO_EMAIL }} \
          --timeout=540s \
          --memory=512MB